server:
  port: 8701

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.52.47:8848
        namespace: 776dcf72-f1df-4595-ad94-671dd4673b06


rx:
  doc: 1.0.0
  swagger:
    enabled: true
    title: swagger-starter组件
    description: Ruixiang
    version: ${rx.doc}
    licenseUrl: http://www.baidu.com
    termsOfServiceUrl: https://github.com/
    dockets:
      order-contol:
        title: order-Swagger2
        description: Order description
        version: ${rx.doc}
        basePackage: com.rx.controller




logging:
  file:
    path: ./logs/${spring.application.name}.log
  config: classpath:log4j2.xml
  level:
    root: info
    sql: info
    web: info
