

spring:
  application:
    name: gateway
  profiles:
    active: jsf
#  config:
#    activate:
#      on-profile: jsf
  cloud:
    nacos:
      discovery:
        group: service
        namespace: ${spring.profiles.active}
        server-addr: ${nacos.address}
      config:
        namespace: ${spring.profiles.active}
        file-extension: yml
        server-addr: ${nacos.address}
        group: ${spring.cloud.nacos.discovery.group}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: userServiceRouter
          uri: lb://user-consumer
          predicates:
            - Path=/api/userService/**
          filters:
            - StripPrefix=2



# ------------服务器配置
---
spring:
  profiles: jsf

nacos:
  address: 47.107.52.47:8848
server:
  port: 8650

---
spring:
  profiles: test
nacos:
  address: 47.107.52.47:8848

---
spring:
  profiles: prod
nacos:
  address: 192.168.100.53:8848

---
