server:
  port: 8600

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.5:8848
        #server-addr: 192.168.199.5:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: userServiceRouter
          uri: lb://user-consumer
          predicates:
            - Path=/api/userService/**
          filters:
            - StripPrefix=2


