
spring:
  application:
    name: @artifactId@
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: 47.107.90.15
    port: 6379
    database: 12
    connect-timeout: 30000
  #redis 单机地址
  redisson: address=192.168.1.204:6379

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      min-idle: 10
      max-pool-size: 12
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 540000
      connection-timeout: 60000

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.rx.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  httpclient:
    enabled: true
    connection-timeout: 10000
    connection-timer-repeat: 10000


logging:
  config: classpath:log4j2-spring.xml

---
spring:
  profiles: dev
server:
  port: 11111
---

spring:
  profiles: test
server:
  port: 11112
---

spring:
  profiles: prod
server:
  port: 11113
---