
spring:
  application:
    name: @artifactId@
  profiles:
    active: dev


logging:
  config: classpath:log4j2-spring.xml

---
spring:
  profiles: dev
server:
  port: 11111
---

spring:
  profiles: test
server:
  port: 11112
---

spring:
  profiles: prod
server:
  port: 11113
---